baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]

  # Directory name of your main content (default is `content/posts`).
  # The list of set content will show up on your index page (baseurl).
  contentTypeName = "content/posts"

  # If you set this to 0, only submenu trigger will be visible.
  showMenuItems = 2

  # Show selector to switch language.
  showLanguageSelector = false

  # Set theme to full screen width.
  fullWidthTheme = true

  # Center theme with default width.
  centerTheme = false

  # If your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option, you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # Set post to show the last updated date.
  # If you use Git, you can set `enableGitInfo` to `true` and then the post will automatically get the last updated date.
  showLastUpdated = false

  # Whether to show a page's estimated reading time.
  readingTime = true

  # Whether to show a table of contents.
  # Can be overridden in a page's front-matter.
  Toc = false

  # Set title for the table of contents.
  # Can be overridden in a page's front-matter.
  TocTitle = "Table of Contents"


[languages]
  [languages.en]
    languageName = "English"
    title = "Terminal"

    [languages.en.params]
      subtitle = "A simple, retro theme for Hugo"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Terminal"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/posts/about"